version: '3.8'

services:
  sec:
    # build:
      # context: .
      # dockerfile: Dockerfile
    image: realtemirov/go-sqlc-grpc-http:test
    container_name: sec
    env_file:
      - .env
    ports:
      - "8083:8083"
    networks:
      - my_network
    restart: always

volumes:
  minio-data:

networks:
  my_network:
    driver: bridge