// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	zero "gopkg.in/guregu/null.v4/zero"
)

type Test struct {
	ID        int64     `json:"id"`
	Name      string    `json:"name"`
	CreatedAt zero.Time `json:"created_at"`
	UpdatedAt zero.Time `json:"updated_at"`
}
