project:
  name: &project_name "go-sqlc-grpc-http"
  version: &version "0.0.1"
  timeout: 3s
  swagger_enabled: false
  cache_timeout: 30m
logging:
  level: debug
  log_first_n: 3
  log_there_after: 10
  log_interval: 1s
  project_name: *project_name
http:
  host: 0.0.0.0
  port: 8080
grpc:
  host: 0.0.0.0
  port: 60000
